In [2]:
import torch

## 数据的基本操作

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape # 张量的形状

torch.Size([12])

In [5]:
x.numel() # 张量的大小

12

In [7]:
X = x.reshape(3,4) #向量转化为矩阵
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X.shape # 查看矩阵的shape

torch.Size([3, 4])

In [9]:
X.numel() #矩阵元素的个数

12

In [10]:
torch.zeros(3,4) #生成3*4的零矩阵

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones(3,3,3) #生成3*3*3的1矩阵

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
torch.randn(3,4) #均值为0，标准差为1的标准正态分布

tensor([[-0.9227, -0.3627,  0.0925, -2.0583],
        [ 0.4102,  1.0985,  0.1997, -1.0640],
        [-0.9872,  0.2065,  1.6798, -0.2848]])

In [15]:
torch.Tensor([[1,2,3],[4,5,6],[7,8,9]]) # python list生成torch tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])