In [2]:
import torch

## 入门

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape # 张量的形状

torch.Size([12])

In [5]:
x.numel() # 张量的大小

12

In [7]:
X = x.reshape(3,4) #向量转化为矩阵
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X.shape # 查看矩阵的shape

torch.Size([3, 4])

In [9]:
X.numel() #矩阵元素的个数

12

In [10]:
torch.zeros(3,4) #生成3*4的零矩阵

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones(3,3,3) #生成3*3*3的1矩阵

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
torch.randn(3,4) #均值为0，标准差为1的标准正态分布

tensor([[-0.9227, -0.3627,  0.0925, -2.0583],
        [ 0.4102,  1.0985,  0.1997, -1.0640],
        [-0.9872,  0.2065,  1.6798, -0.2848]])

In [15]:
torch.Tensor([[1,2,3],[4,5,6],[7,8,9]]) # python list生成torch tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

## 运算

In [17]:
x = torch.tensor([1.0, 2, 4, 6])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x*y   # 加减乘除 幂

(tensor([3., 4., 6., 8.]),
 tensor([-1.,  0.,  2.,  4.]),
 tensor([ 2.,  4.,  8., 12.]),
 tensor([0.5000, 1.0000, 2.0000, 3.0000]),
 tensor([ 2.,  4.,  8., 12.]))

In [18]:
torch.exp(x)   # ln()

tensor([  2.7183,   7.3891,  54.5981, 403.4288])

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3],[1, 2, 3, 4],[4,3,2,1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)   # tensor 的拼接操作

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [20]:
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [21]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
X.sum() # 求全部元素的和

tensor(66.)

In [23]:
X.sum(axis=0) # 0维度求和

tensor([12., 15., 18., 21.])

In [25]:
X.sum(axis=1) #1维度求和

tensor([ 6., 22., 38.])

## 其他

In [26]:
# 广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

In [27]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [28]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)